// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package generated

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func GadgetResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "author-defined id, must not be overwritten",
				MarkdownDescription: "author-defined id, must not be overwritten",
			},
		},
	}
}

type GadgetModel struct {
	Id types.String `tfsdk:"id"`
}
